"""Add image_url to currency

Revision ID: 102ae6ea19a8
Revises: 
Create Date: 2025-12-09 15:10:26.951968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102ae6ea19a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'currencies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currencies', type_='unique')
    op.drop_column('currencies', 'image_url')
    # ### end Alembic commands ###
